services:
  jupyter:
    build:
      context: ./.dockercontainer        # <-- build context is the folder with Dockerfile
      dockerfile: Dockerfile
    container_name: bfast
    ports:
      - "8888:8888"                      # host:container
    volumes:
      - .:/home/jovyan/work              # mount entire project
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    restart: unless-stopped
